### ISSUE TITLE
Download links broken

### ISSUE THREAD

**Issue by shivpalkang** [jpcima/DelayArchitect#31]
When clicked, the download links return a 404 error:

> GitHub produced an error for the download of artifact #93365178.
> Usually this means that the artifact has expired (>90 days).

**Comment by jpcima** [comment]
The artifacts are remade, should be ok now.

**Comment by itsjustforschool** [comment]
It happened again.

**Comment by jpcima** [comment]
> It happened again.

Yes, the artifacts seem to disappear after some months.
I pushed a commit that updates Juce to 7.0.1, so there will be new artifacts in a moment.

**Comment by andy-twosticks** [comment]
Expired again, sorry.
